#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1597034898 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
#presskit_download_link                    : https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           :  Surf your favorite websites with clarity.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Sufiyan Yasa
your_link                                 : https://sufiyanyasa.com
your_city                                 : Malaysia
email_address                             : me@sufiyanyasa.com
facebook_username                         :
instagram_username                        :
twitter_username                          : sufiyanyasa
github_username                           : xr1337
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Tweak Font Sizes
    description                           : Set your preferred minimum font size. The extension will update the text size on Safari.
    fontawesome_icon_name                 : text-height

  - title                                 : Override Font family
    description                           : Websites will use your preferred font when rendering text. No more font surprises!
    fontawesome_icon_name                 : font

  - title                                 : Tweak line heights, weight and kerning ( pro )
    description                           : Automatically updates Safari text upon website visit. You can also change the line height, font weight and kerning of text.
    fontawesome_icon_name                 : text-width

  - title                                 : iCloud Support
    description                           : Font size settings will be sync to all your iCloud devices.
    fontawesome_icon_name                 : cloud

  - title                                 : Change App icon and appearance
    description                           : Don't like my color choice, choose from a list of different colors.
    fontawesome_icon_name                 : palette

  - title                                 : No Tracking
    description                           : Respects your privacy. It will never add tracking
    fontawesome_icon_name                 : user-secret

  - title                                 : Dark mode
    description                           : Supports dark mode out of the box
    fontawesome_icon_name                 : moon


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage2.jpeg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown

include: [".well-known"]
